In [5]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 500) #capability

In [6]:
df = pd.read_csv("/content/nasa_exoplanet_intelligence.csv")

In [7]:
df.head()

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
0,Kepler-1167 b,Kepler-1167,1,1,Transit,2016.0,Kepler,1.003934,1.710000,3.570,...,298.302660,47.693965,0,Super-Earth,False,False,False,Far(500-2kpc),K-type,Short(1-10d)
1,Kepler-1740 b,Kepler-1740,1,1,Transit,2021.0,Kepler,8.172400,3.323214,11.000,...,293.873663,38.922455,0,Mini-Neptune,False,False,True,Far(500-2kpc),G-type(Sun-like),Short(1-10d)
2,Kepler-1581 b,Kepler-1581,1,1,Transit,2016.0,Kepler,6.283855,0.800000,0.437,...,287.371320,39.603623,0,Sub-Earth,False,False,False,Mid(100-500pc),F-type,Short(1-10d)
3,Kepler-644 b,Kepler-644,1,1,Transit,2016.0,Kepler,3.173917,3.150000,10.100,...,295.475702,43.493112,0,Mini-Neptune,False,False,False,Far(500-2kpc),F-type,Short(1-10d)
4,Kepler-1752 b,Kepler-1752,1,1,Transit,2021.0,Kepler,56.358501,4.540605,18.700,...,290.854140,51.222743,0,Neptune-like,False,False,True,Far(500-2kpc),G-type(Sun-like),Medium(10-100d)

In [8]:
df.columns

Index(['planet_name', 'host_star', 'n_stars', 'n_planets', 'discovery_method',
       'disc_year', 'disc_facility', 'orbital_period_days',
       'planet_radius_earth', 'planet_mass_earth', 'equilibrium_temp_k',
       'orbital_eccentricity', 'semi_major_axis_au', 'star_temp_k',
       'star_radius_sun', 'star_mass_sun', 'star_age_gyr',
       'star_surface_gravity', 'star_metallicity', 'dist_from_earth_pc',
       'star_vmag', 'ra', 'dec', 'controversial_flag', 'planet_type',
       'habitable_zone_flag', 'multi_planet_system', 'is_recent_discovery',
       'dist_category', 'star_type', 'orbital_period_cat'],
      dtype='object')

In [9]:
df.shape

(6150, 31)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   planet_name           6150 non-null   object
 1   host_star             6150 non-null   object
 2   n_stars               6150 non-null   int64
 3   n_planets             6150 non-null   int64
 4   discovery_method      6150 non-null   object
 5   disc_year             6149 non-null   float64
 6   disc_facility         6150 non-null   object
 7   orbital_period_days   5816 non-null   float64
 8   planet_radius_earth   6100 non-null   float64
 9   planet_mass_earth     6119 non-null   float64
 10  equilibrium_temp_k    4587 non-null   float64
 11  orbital_eccentricity  5212 non-null   float64
 12  semi_major_axis_au    5834 non-null   float64
 13  star_temp_k           5860 non-null   float64
 14  star_radius_sun       5836 non-null   float64
 15  star_mass_sun         6142 non-null   float64
 16  star_age_gyr          4839 non-null   float64
 17  star_surface_gravity  5832 non-null   float64
 18  star_metallicity      5600 non-null   float64
 19  dist_from_earth_pc    6123 non-null   float64
 20  star_vmag             5855 non-null   float64
 21  ra                    6150 non-null   float64
 22  dec                   6150 non-null   float64
 23  controversial_flag    6150 non-null   int64
 24  planet_type           6150 non-null   object
 25  habitable_zone_flag   6150 non-null   bool
 26  multi_planet_system   6150 non-null   bool
 27  is_recent_discovery   6150 non-null   bool
 28  dist_category         6150 non-null   object
 29  star_type             6150 non-null   object
 30  orbital_period_cat    6150 non-null   object
dtypes: bool(3), float64(17), int64(3), object(8)
memory usage: 1.3+ MB

In [11]:
df['discovery_method'].value_counts()

discovery_method
Transit                          4517
Radial Velocity                  1182
Microlensing                      275
Imaging                            94
Transit Timing Variations          39
Eclipse Timing Variations          17
Orbital Brightness Modulation       9
Pulsar Timing                       8
Astrometry                          6
Pulsation Timing Variations         2
Disk Kinematics                     1
Name: count, dtype: int64

In [14]:
df['discovery_method'].value_counts().count()

np.int64(11)

In [12]:
df.isnull().sum()

planet_name                0
host_star                  0
n_stars                    0
n_planets                  0
discovery_method           0
disc_year                  1
disc_facility              0
orbital_period_days      334
planet_radius_earth       50
planet_mass_earth         31
equilibrium_temp_k      1563
orbital_eccentricity     938
semi_major_axis_au       316
star_temp_k              290
star_radius_sun          314
star_mass_sun              8
star_age_gyr            1311
star_surface_gravity     318
star_metallicity         550
dist_from_earth_pc        27
star_vmag                295
ra                         0
dec                        0
controversial_flag         0
planet_type                0
habitable_zone_flag        0
multi_planet_system        0
is_recent_discovery        0
dist_category              0
star_type                  0
orbital_period_cat         0
dtype: int64

In [13]:
df.describe().round() #borra los decimales

,n_stars,n_planets,disc_year,orbital_period_days,planet_radius_earth,planet_mass_earth,equilibrium_temp_k,orbital_eccentricity,semi_major_axis_au,star_temp_k,star_radius_sun,star_mass_sun,star_age_gyr,star_surface_gravity,star_metallicity,dist_from_earth_pc,star_vmag,ra,dec,controversial_flag
count,6150.0,6150.0,6149.0,5816.0,6100.0,6119.0,4587.0,5212.0,5834.0,5860.0,5836.0,6142.0,4839.0,5832.0,5600.0,6123.0,5855.0,6150.0,6150.0,6150.0
mean,1.0,2.0,2017.0,73594.0,6.0,407.0,913.0,0.0,16.0,5398.0,2.0,1.0,4.0,4.0,0.0,712.0,13.0,233.0,18.0,0.0
std,0.0,1.0,5.0,5273718.0,5.0,1143.0,464.0,0.0,349.0,1747.0,4.0,0.0,3.0,0.0,0.0,1212.0,3.0,92.0,37.0,0.0
min,1.0,1.0,1992.0,0.0,0.0,0.0,34.0,0.0,0.0,415.0,0.0,0.0,0.0,1.0,-1.0,1.0,1.0,0.0,-88.0,0.0
25%,1.0,1.0,2014.0,4.0,2.0,4.0,566.0,0.0,0.0,4905.0,1.0,1.0,2.0,4.0,-0.0,101.0,11.0,173.0,-11.0,0.0
50%,1.0,1.0,2016.0,11.0,3.0,9.0,818.0,0.0,0.0,5546.0,1.0,1.0,4.0,4.0,0.0,377.0,13.0,285.0,39.0,0.0
75%,1.0,2.0,2021.0,40.0,12.0,191.0,1164.0,0.0,0.0,5900.0,1.0,1.0,6.0,5.0,0.0,836.0,15.0,293.0,45.0,0.0
max,4.0,8.0,2026.0,402000000.0,87.0,9535.0,4050.0,1.0,19000.0,57000.0,88.0,11.0,16.0,8.0,1.0,8500.0,45.0,360.0,87.0,1.0